# BEWARE all lines starting with # are disabled, just placeholders. If you need to set the option remove the initial #
#port: 80
#max_kbps: 1000
#max_kbps_per_ip: 500
#log:
#error_log:
#zip-calculate-size-for-seconds: 1
#open_browser_at_start: false
#https_port: 443  # https will work only if you give a valid certificate and private key
#cert: filepath
#private_key: filepath
mime:
  "*.jpg|*.png|*.mp3|*.txt": auto
disable_plugins: [ 'theme-example', 'middleware-example', 'download-counter' ]
plugins_config:
  middleware-example:
    message: ciao
vfs:
  children:
    - name: f1
      children:
        - name: f2
          children:
            - source: tests/alfa.txt
        - name: pic
          mime: png
          source: tests/page/gpl.png
        - name: page
          default: index.html
          source: tests/page
    - name: proxy
      source: https://raw.githubusercontent.com/nodejs/node/master/README.md
    - name: for-admins
      perm:
        admin: r
      children:
        - source: tests/alfa.txt
